### ISSUE TITLE
The picture of  structure of Reactive values is wrong.

### ISSUE THREAD

**Issue by hepin1989** [reactivemanifesto/reactivemanifesto#112]
![image](https://user-images.githubusercontent.com/501740/36656450-7b8308dc-1b03-11e8-8b6e-4560487930b9.png)

did not match the picture in RPD(Reactive Design Pattern)

![image](https://user-images.githubusercontent.com/501740/36656501-ab7a8f24-1b03-11e8-8b0a-3d06a6bfc7a6.png)

As @rkuhn 's reply, the picture is wrong and should alias with that in the RDP.

**Comment by rkuhn** [comment]
Sorry for the delay, perhaps I should add some background: The origin of this change to the diagram is @viktorklang if I remember correctly, three to four years ago. I immediately liked it and extended it to the form used in Reactive Design Patterns: this design approach yields more values than just responsiveness. I can see both associations of form and meaning making sense, they focus on slightly different aspects.

The current diagram on the manifesto site makes it clear that a message driven architecture is just a means to achieve two ends—elasticity and resilience. These two outcomes are then taken to describe the form (or shape) of an application.

The diagram from Reactive Design Patterns emphasizes that elasticity and resilience are themselves only means to an end, they are not a goal by themselves. Due to the distributed nature required by both elasticity and resilience, the shape of information flow—the form of the application—is message driven.

I clearly prefer the second choice, not only due to its focus but also since elasticity and resilience are farther away from the concrete form or shape of a program, these qualities describe it on a metalevel. Hence I propose to change the diagram.

**Comment by hepin1989** [comment]
I hope this to be fixed .

>As it might be noticed from the diagram above, the main value for any business implemented with a distributed system is Responsiveness. It relies on the principal forms that allows achieving it. In turn, fundamental forms of achieving Responsive System are Elasticity and Resilience achieving of which means employing Message-Driven communication.
here is my derived explanation of RM
https://www.reactivemanifesto.org/images/reactive-traits.svg
just to joke because I know that you preffere to exchange those words :D

Otherwise, the current diagram will continuse cause some misunderstanding.

@jboner

**Comment by ktoso** [comment]
If you can come up with the circular image modified somehow to show the expanded reasoning that'd be the best... The image has stuck in peoples minds quite a bit by now, so going for a completely different style may be difficult. Any ideas how to improve the circle the additional information?

**Comment by hepin1989** [comment]
@ktoso The problem is not the circular or rectangle ,but the order of the **means** and **forms** should be swapped.

**Comment by neomaclin** [comment]
Just a bit of background on this, we spotted this when translating RDP to Chinese. It is not about the shape or the flow of the original image, but rather where to place **means** and **forms**. As @rkuhn rightfully put, the **focus**.

**Comment by OlegDokuka** [comment]
Hah, actually it is something from the upcomming book 😂 lol.

**Comment by hepin1989** [comment]
@OlegDokuka I am about to at you:), we spotted this when we was translating the book.

**Comment by OlegDokuka** [comment]
Actually, what about the following improvement? : 
![method-draw-image 3](https://user-images.githubusercontent.com/5380167/40408812-761ebe66-5e71-11e8-8c38-d66a0ae70aa7.png)

**Comment by OlegDokuka** [comment]
Also, what do you think about the following statement: 

> As it might be noticed from the diagram above, the primary value for any business implemented with a system is **Responsiveness**. In turn, achieving of Responsive, Maintainable, and Extensible System _means_ following foundational techniques like Elasticity and Resilience. In turn, one of the fundamental forms of attaining Responsive, Elastic and Resilient System is employing **Message-Driven** communication.

Additional we may emphasize that **means** regarding Elasticity and Resilience in that context means that Reactive System might be achieved without elasticity just by configuring proper Resilience. It might be replicated System but not elastic, and Responsiveness will be achieved in that case by managing backpressure properly. Is it a good example?

**Comment by hepin1989** [comment]
@neomaclin cc

**Comment by rkuhn** [comment]
Sorry for the misattribution, then :-) And yes, I also recall that the discussion took place in the old prison.

**Comment by jboner** [comment]
It doesn't matter. I was just teasing with you. But I'll make sure it gets updated.

**Comment by jboner** [comment]
@OlegDokuka 
Can you email me the SVG file?
Firstname@lightbend.com
Thanks.

**Comment by OlegDokuka** [comment]
@jboner sure

**Comment by ktoso** [comment]
> The problem is not the circular or rectangle, but the order of the means and forms should be swapped.

I see, I missed that

**Comment by OlegDokuka** [comment]
@jboner done

**Comment by jboner** [comment]
Got it. Thanks.

**Comment by jboner** [comment]
@rasummer Could you update the image on the manifesto site? I sent an email with the SVG some time ago.

**Comment by ktoso** [comment]
Attempted to ping Richard :)

**Comment by ktoso** [comment]
@rasummer

**Comment by rasummer** [comment]
Scheduled for build out next week. We will be creating the image and translating it for all the languages.

**Comment by rasummer** [comment]
We've added and deployed the translated image with the 'Maintainable' and 'Extensible' elements. 

We are also now translating the Value/Means/Form part of the image, as we realized this too should be translated.

**Comment by rasummer** [comment]
Deployed

**Comment by ktoso** [comment]
Awesome, thanks @rasummer :)
