### ISSUE TITLE
Github signup does not work

### ISSUE THREAD

**Issue by synox** [reactivemanifesto/reactivemanifesto#98]
I get redirected to an empty page after github auth.

**Comment by jboner** [comment]
@synox Is this still the case?

**Comment by synox** [comment]
still the same for me. 
![image](https://user-images.githubusercontent.com/2250964/28940775-15281970-7896-11e7-92a9-b7b9737cb511.png)

**Comment by jboner** [comment]
When you refresh the site, have you been added to the signatories page?

**Comment by synox** [comment]
No, still not on the list

**Comment by jboner** [comment]
@jroper Any ideas?

**Comment by jroper** [comment]
Hi @synox,

I can only reproduce this if I try to access the website using https, GitHub sign in redirects you back to the http site which is not allowed to access the window opener because it was https. Doing so however requires ignoring an SSL error saying that the domain name is wrong. Did you do this? Or do you plugins that might be automatically switching you to https? We don't support https on reactive manifesto at the moment.

Other possibilities include using a different domain name to access the site (though I'm not sure how you could have done that accidentally), having a JavaScript disabled (though this would probably have prevented you from even attempting to log in in the first place), or having some weird browser security configuration that's blocking child windows from accessing their opener.

If it's none of the above, then can you answer the questions below:

* Does it just happen in Firefox, or does it happen in all browsers?
* What version of Firefox are you using?
* When you get the blank page, are there any errors in the JavaScript console (accessible through the developer tools - ie right click on the page and click "Inspect element", then click on the console tab)? If so, please paste them in full here.

Cheers,

James

**Comment by synox** [comment]
I did some more testing. I did't have a "Name" in my Github Account. 

When I add a name in the profile it works! Does a missing name trigger an error?

**Comment by jroper** [comment]
Thanks @synox, that would likely explain it, our parsing of GitHub profile data assumes that the name field will always be present. I'll update it to make it optional, and I'll also update the UI so that it renders any errors encountered, at this step, this will make diagnosis of similar errors easier in future.

**Comment by jroper** [comment]
Issue fixed here:

https://github.com/reactivemanifesto/website-manifesto/commit/e4af5afdfca3f2415b8a1e5598bb08fc6915ebe6

Also, now error reporting is better, this is the message you would see now (if I hadn't have fixed the bug):

![manifesto-error](https://user-images.githubusercontent.com/105833/29443150-8390b5a0-8419-11e7-9088-a7ae4661c161.png)
